// Feho's Motocycle Road rota arşivi.
// Yeni rota eklemek için bu listedeki bir objeyi kopyala, id/name/stops/coordinates alanlarını doldur.
// Google Maps kısa linklerinden otomatik koordinat çekilmez; yaklaşık yazılan noktalar `approximate: true` ile işaretlendi.

window.FEHO_ROUTES = [
  {
    id: "ankara-camkoru-beypazari-loop",
    name: "Ankara - Çamkoru - Beypazarı Loop",
    description: "Ankara çıkışlı, orman yolları, yayla havası ve Beypazarı dönüş keyfini tek güne sığdıran uzun premium tur.",
    category: "tam gün",
    startPoint: "Başlangıç / Ankara batı çıkışı",
    endPoint: "Raci Bademli Parkı / Ankara dönüş",
    distanceKm: 360,
    estimatedDuration: "5 sa 30 dk sürüş",
    rideMinutes: 330,
    breakMinutes: 120,
    totalMinutes: 450,
    difficulty: "orta",
    recommendedSeason: "İlkbahar, yaz, sonbahar",
    roadCharacter: "Orman geçişleri, yayla bağlantıları, virajlı asfalt ve ilçe içi sakin tempo.",
    fuelServiceNote: "Kızılcahamam, Beypazarı ve Ayaş yakıt/servis için en güvenli noktalar.",
    googleMapsUrl: "https://maps.app.goo.gl/5y3ds12TfeYtYML37",
    image: "assets/hero-cover.jpeg",
    isFavorite: true,
    notes: [
      "Yayla bağlantılarında asfalt kalitesi değişebilir.",
      "Beypazarı sonrası dönüşte gün batımı saatini hesapla."
    ],
    rideAdvice: "Sabah erken çık, Çamkoru ve Eğriova tarafında tempoyu düşür; manzara duraklarını kısa ama sık tut.",
    riskWarnings: "Yayla yollarında mıcır, traktör geçişi ve ani sis olabilir. Orman içi virajlarda kör noktalara dikkat.",
    coffeeFoodPhoto: "Kızılcahamam kahve molası, Çamkoru orman fotoğrafı, Beypazarı yemek/dinlenme molası.",
    stops: [
      {
        name: "Başlangıç / Ankara",
        description: "Kullanıcının verdiği başlangıç koordinatı.",
        note: "Depo, lastik basıncı ve zincir kontrolü için son sakin nokta.",
        coords: [39.8820606, 32.6893723],
        favorite: true
      },
      {
        name: "Kızılcahamam",
        description: "İlk büyük mola ve yakıt alternatifi.",
        note: "Kısa kahve molası için iyi durak.",
        coords: [40.4697, 32.6506],
        approximate: true
      },
      {
        name: "Çamlıdere",
        description: "Yayla ve orman etaplarına geçiş kapısı.",
        note: "Market ve kısa ihtiyaç molası planlanabilir.",
        coords: [40.4896, 32.4746],
        approximate: true
      },
      {
        name: "Çamkoru Tabiat Parkı",
        description: "Orman içinde sakin tempo ve fotoğraf molası.",
        note: "Hafta sonu kalabalık olabilir.",
        coords: [40.5146, 32.4836],
        approximate: true,
        favorite: true
      },
      {
        name: "Ara koordinat noktası",
        description: "Kullanıcının rotada verdiği manuel koordinat.",
        note: "Bu nokta hassas koordinat olarak korundu.",
        coords: [40.4478629, 32.3049811]
      },
      {
        name: "Çamlıdere Benli Yaylası",
        description: "Yayla havası ve açık manzara.",
        note: "Yol şartı mevsime göre değişebilir.",
        coords: [40.555, 32.32],
        approximate: true
      },
      {
        name: "Eğriova Tabiat Parkı",
        description: "Göl/orman hissi veren rota durağı.",
        note: "Fotoğraf molası için değerli durak.",
        coords: [40.62, 32.064],
        approximate: true,
        favorite: true
      },
      {
        name: "Beypazarı",
        description: "Yemek, dinlenme ve yakıt için ana durak.",
        note: "Uzun dönüş öncesi mola süresini burada kullan.",
        coords: [40.1675, 31.9211],
        approximate: true
      },
      {
        name: "Ayaş",
        description: "Ankara dönüşünden önce son ilçe molası.",
        note: "Akşam dönüşünde trafik kontrolü yap.",
        coords: [40.0193, 32.3335],
        approximate: true
      },
      {
        name: "Raci Bademli Parkı / Ankara dönüş",
        description: "Dönüş ve kapanış noktası.",
        note: "Rotayı burada bitir, ekipmanları toparla.",
        coords: [39.8820606, 32.6893723]
      }
    ]
  },
  {
    id: "ayas-gudul-karagol-yayla",
    name: "Ayaş - Güdül - Karagöl Yayla Rotası",
    description: "Göletler, kamp noktaları ve kuzey Ankara yaylalarını bağlayan uzun, keşif hissi yüksek rota.",
    category: "kamp",
    startPoint: "Başlangıç / Ankara batı çıkışı",
    endPoint: "Yıldırım Elören Köyü Yaylası",
    distanceKm: 330,
    estimatedDuration: "5 sa sürüş",
    rideMinutes: 300,
    breakMinutes: 150,
    totalMinutes: 450,
    difficulty: "zor",
    recommendedSeason: "Yaz ve erken sonbahar",
    roadCharacter: "Gölet bağlantıları, kırsal asfalt, kamp yolu ve yayla geçişleri.",
    fuelServiceNote: "Ayaş, Güdül ve Kızılcahamam dışında servis imkanı sınırlı kabul edilmeli.",
    googleMapsUrl: "https://maps.app.goo.gl/hmC6p52MifLXf7yc8",
    image: "assets/hero-cover.jpeg",
    isFavorite: true,
    notes: [
      "Kamp ekipmanı varsa yük dağılımını çıkıştan önce kontrol et.",
      "Yayla ve mesire alanlarında telefon çekimi zayıflayabilir."
    ],
    rideAdvice: "Güdül sonrası yakıtı ve suyu tamamla; Karagöl ve yayla etaplarında düşük vites, sakin çizgi ve bol mesafe bırak.",
    riskWarnings: "Yayla bağlantılarında gevşek zemin, hayvan geçişi ve ani hava değişimi olabilir.",
    coffeeFoodPhoto: "Ayaş kısa kahve, No9 Camping dinlenme, Karagöl fotoğraf ve Yıldırım Elören yayla gün batımı.",
    stops: [
      {
        name: "Başlangıç / Ankara",
        description: "Kullanıcının verdiği başlangıç koordinatı.",
        note: "Uzun rota için depo tam başlamak iyi olur.",
        coords: [39.8820631, 32.6892643],
        favorite: true
      },
      {
        name: "Ayaş",
        description: "Batı çıkışındaki ilk ana durak.",
        note: "Kahve ve kısa ihtiyaç molası.",
        coords: [40.0193, 32.3335],
        approximate: true
      },
      {
        name: "Kirazdibi Göleti",
        description: "Gölet manzaralı ara durak.",
        note: "Fotoğraf için kısa mola.",
        coords: [40.158, 32.257],
        approximate: true,
        favorite: true
      },
      {
        name: "Güdül",
        description: "Kırsal etap öncesi toparlanma noktası.",
        note: "Su ve atıştırmalık tamamla.",
        coords: [40.2104, 32.2453],
        approximate: true
      },
      {
        name: "No9 Camping",
        description: "Kamp ve dinlenme karakterli durak.",
        note: "Uzun mola için uygun rota noktası.",
        coords: [40.245, 32.24],
        approximate: true,
        favorite: true
      },
      {
        name: "Kızılcahamam",
        description: "Servis, yakıt ve yemek için güçlü merkez.",
        note: "Sonraki göl/yayla kısmı için hazırlık.",
        coords: [40.4697, 32.6506],
        approximate: true
      },
      {
        name: "Füreyya Göleti",
        description: "Sakin gölet geçişi.",
        note: "Zemin kontrolü yaparak yaklaş.",
        coords: [40.535, 32.595],
        approximate: true
      },
      {
        name: "Karagöl",
        description: "Rotanın en fotojenik göl duraklarından biri.",
        note: "Hafta sonu kalabalık olabilir.",
        coords: [40.569, 32.642],
        approximate: true,
        favorite: true
      },
      {
        name: "Ay Kayası Mesire Alanı",
        description: "Mesire alanı ve kısa mola noktası.",
        note: "Dönüş planını burada tekrar kontrol et.",
        coords: [40.585, 32.705],
        approximate: true
      },
      {
        name: "Yıldırım Elören Köyü Yaylası",
        description: "Yayla bitiş noktası.",
        note: "Hava kararmadan dönüş ya da kamp kararı ver.",
        coords: [40.64, 32.78],
        approximate: true,
        favorite: true
      }
    ]
  },
  {
    id: "shortlink-srgczrt5",
    name: "Rota 01 - Kısa Link Arşivi",
    description: "Kısa Google Maps linki eklendi; duraklar ve koordinatlar manuel tamamlanacak.",
    category: "kısa tur",
    startPoint: "Planlanacak",
    endPoint: "Planlanacak",
    distanceKm: null,
    estimatedDuration: "Planlanacak",
    rideMinutes: null,
    breakMinutes: null,
    totalMinutes: null,
    difficulty: "planlanacak",
    recommendedSeason: "Planlanacak",
    roadCharacter: "Koordinatlar eklenince belirlenecek.",
    fuelServiceNote: "Yakıt/servis notu manuel eklenecek.",
    googleMapsUrl: "https://maps.app.goo.gl/SRgcZRt5fKw2LBr96",
    image: "assets/hero-cover.jpeg",
    isPlaceholder: true,
    notes: ["Bu kayıt 10 rotalık arşivde yer tutar; harita çizimi için koordinat bekliyor."],
    rideAdvice: "Rota koordinatları eklenince sürüş tavsiyesi güncellenecek.",
    riskWarnings: "Risk notları manuel keşif sonrası yazılacak.",
    coffeeFoodPhoto: "Kahve, yemek ve fotoğraf noktaları eklenecek.",
    stops: []
  },
  {
    id: "shortlink-4snox352",
    name: "Rota 02 - Kısa Link Arşivi",
    description: "Kısa Google Maps linki eklendi; Leaflet çizimi için manuel koordinat bekliyor.",
    category: "virajlı yol",
    startPoint: "Planlanacak",
    endPoint: "Planlanacak",
    distanceKm: null,
    estimatedDuration: "Planlanacak",
    rideMinutes: null,
    breakMinutes: null,
    totalMinutes: null,
    difficulty: "planlanacak",
    recommendedSeason: "Planlanacak",
    roadCharacter: "Viraj karakteri koordinatlar eklenince netleşecek.",
    fuelServiceNote: "Yakıt/servis notu manuel eklenecek.",
    googleMapsUrl: "https://maps.app.goo.gl/4snox352yB9KXWYT9",
    image: "assets/hero-cover.jpeg",
    isPlaceholder: true,
    notes: ["Bu kısa link rota verisi olarak saklandı; duraklar daha sonra doldurulabilir."],
    rideAdvice: "Manuel durak listesi eklendiğinde güncellenecek.",
    riskWarnings: "Yol riski henüz girilmedi.",
    coffeeFoodPhoto: "Keşif noktaları eklenecek.",
    stops: []
  },
  {
    id: "shortlink-usqazh6",
    name: "Rota 04 - Kısa Link Arşivi",
    description: "Google Maps kısa linki arşivlendi; durak koordinatları daha sonra girilecek.",
    category: "yayla",
    startPoint: "Planlanacak",
    endPoint: "Planlanacak",
    distanceKm: null,
    estimatedDuration: "Planlanacak",
    rideMinutes: null,
    breakMinutes: null,
    totalMinutes: null,
    difficulty: "planlanacak",
    recommendedSeason: "Planlanacak",
    roadCharacter: "Yayla/bağlantı karakteri manuel veri sonrası yazılacak.",
    fuelServiceNote: "Servis notu eksik.",
    googleMapsUrl: "https://maps.app.goo.gl/UsQAzH6u6wf3YAoQ9?g_st=iw",
    image: "assets/hero-cover.jpeg",
    isPlaceholder: true,
    notes: ["Kısa link korundu, koordinat çıkarımı otomatik yapılmadı."],
    rideAdvice: "Planlanacak.",
    riskWarnings: "Planlanacak.",
    coffeeFoodPhoto: "Planlanacak.",
    stops: []
  },
  {
    id: "shortlink-ergphj3-06",
    name: "Rota 06 - Kısa Link Arşivi",
    description: "Aynı kısa link iki ayrı arşiv kaydından ilki olarak tutuldu.",
    category: "göl",
    startPoint: "Planlanacak",
    endPoint: "Planlanacak",
    distanceKm: null,
    estimatedDuration: "Planlanacak",
    rideMinutes: null,
    breakMinutes: null,
    totalMinutes: null,
    difficulty: "planlanacak",
    recommendedSeason: "Planlanacak",
    roadCharacter: "Koordinatlar eklenince belirlenecek.",
    fuelServiceNote: "Yakıt/servis notu manuel eklenecek.",
    googleMapsUrl: "https://maps.app.goo.gl/eRgPHj3Bpx7Hq6RP7",
    image: "assets/hero-cover.jpeg",
    isPlaceholder: true,
    notes: ["Kullanıcının verdiği listede bu kısa link tekrar ediyor; bu kayıt ilk kopya."],
    rideAdvice: "Planlanacak.",
    riskWarnings: "Planlanacak.",
    coffeeFoodPhoto: "Planlanacak.",
    stops: []
  },
  {
    id: "shortlink-ergphj3-07",
    name: "Rota 07 - Kısa Link Arşivi",
    description: "Aynı kısa link ikinci rota kaydı olarak girildi; koordinatlar manuel tamamlanacak.",
    category: "tam gün",
    startPoint: "Planlanacak",
    endPoint: "Planlanacak",
    distanceKm: null,
    estimatedDuration: "Planlanacak",
    rideMinutes: null,
    breakMinutes: null,
    totalMinutes: null,
    difficulty: "planlanacak",
    recommendedSeason: "Planlanacak",
    roadCharacter: "Koordinatlar eklenince belirlenecek.",
    fuelServiceNote: "Yakıt/servis notu manuel eklenecek.",
    googleMapsUrl: "https://maps.app.goo.gl/eRgPHj3Bpx7Hq6RP7",
    image: "assets/hero-cover.jpeg",
    isPlaceholder: true,
    notes: ["Verilen listede kısa link tekrar ettiği için ayrı id ile ikinci kayıt oluşturuldu."],
    rideAdvice: "Planlanacak.",
    riskWarnings: "Planlanacak.",
    coffeeFoodPhoto: "Planlanacak.",
    stops: []
  },
  {
    id: "shortlink-r6hys8",
    name: "Rota 08 - Kısa Link Arşivi",
    description: "Kısa link hazır; rota kartı ve KML placeholder olarak indirilebilir.",
    category: "kamp",
    startPoint: "Planlanacak",
    endPoint: "Planlanacak",
    distanceKm: null,
    estimatedDuration: "Planlanacak",
    rideMinutes: null,
    breakMinutes: null,
    totalMinutes: null,
    difficulty: "planlanacak",
    recommendedSeason: "Planlanacak",
    roadCharacter: "Kamp karakteri manuel veri sonrası yazılacak.",
    fuelServiceNote: "Yakıt/servis notu manuel eklenecek.",
    googleMapsUrl: "https://maps.app.goo.gl/R6hyS8Ucq9dtmymw9",
    image: "assets/hero-cover.jpeg",
    isPlaceholder: true,
    notes: ["Koordinat girilene kadar haritada çizgi oluşmaz."],
    rideAdvice: "Planlanacak.",
    riskWarnings: "Planlanacak.",
    coffeeFoodPhoto: "Planlanacak.",
    stops: []
  },
  {
    id: "shortlink-hldd8",
    name: "Rota 09 - Kısa Link Arşivi",
    description: "Kısa Google Maps linki saklandı; durak listesi eklemeye hazır.",
    category: "kısa tur",
    startPoint: "Planlanacak",
    endPoint: "Planlanacak",
    distanceKm: null,
    estimatedDuration: "Planlanacak",
    rideMinutes: null,
    breakMinutes: null,
    totalMinutes: null,
    difficulty: "planlanacak",
    recommendedSeason: "Planlanacak",
    roadCharacter: "Koordinatlar eklenince belirlenecek.",
    fuelServiceNote: "Yakıt/servis notu manuel eklenecek.",
    googleMapsUrl: "https://maps.app.goo.gl/HLDD8sg5Wtj9BZMK6",
    image: "assets/hero-cover.jpeg",
    isPlaceholder: true,
    notes: ["Bu rota veri yapısında hazır, sadece durak/koordinat bekliyor."],
    rideAdvice: "Planlanacak.",
    riskWarnings: "Planlanacak.",
    coffeeFoodPhoto: "Planlanacak.",
    stops: []
  },
  {
    id: "shortlink-b3f4v",
    name: "Rota 10 - Kısa Link Arşivi",
    description: "Onuncu rota kısa linki eklendi; KML çıktısında planlama notu ile yer alır.",
    category: "virajlı yol",
    startPoint: "Planlanacak",
    endPoint: "Planlanacak",
    distanceKm: null,
    estimatedDuration: "Planlanacak",
    rideMinutes: null,
    breakMinutes: null,
    totalMinutes: null,
    difficulty: "planlanacak",
    recommendedSeason: "Planlanacak",
    roadCharacter: "Koordinatlar eklenince belirlenecek.",
    fuelServiceNote: "Yakıt/servis notu manuel eklenecek.",
    googleMapsUrl: "https://maps.app.goo.gl/b3f4VUrnfoiPCqnf8",
    image: "assets/hero-cover.jpeg",
    isPlaceholder: true,
    notes: ["10 rotalık arşivin son kısa link kaydı."],
    rideAdvice: "Planlanacak.",
    riskWarnings: "Planlanacak.",
    coffeeFoodPhoto: "Planlanacak.",
    stops: []
  }
];

window.FEHO_ROUTES.forEach((route) => {
  route.coordinates = route.stops
    .filter((stop) => Array.isArray(stop.coords))
    .map((stop) => stop.coords);
});
